name: 'Dispatch workflow'
description: "Builds chain of celantur images"
inputs:
  organisation:
    required: false
    default: "celantur"
    description: "Organisation name (probably celantur unless you are a traitor)"
  repo:
    required: true
    description: "Repository name"
  token:
    required: true
    description: "Personal access token for the user who has access to the repository"
  runner:
    required: true
    description: "Runner name to be used in the workflow"
  event-type:
    required: true
    description: "Event type to be dispatched"
  additional-client-payload:
    required: false
    description: "Client payload to be sent with the event"
  
runs:
  using: composite
  steps:
    - name: "Info"
      shell: bash
      env:
        ORG: ${{ inputs.organisation }}
        REPO: ${{ inputs.repo }}
        TOKEN: ${{ inputs.token }}
        RUNNER: ${{ inputs.runner }}
        EVENT_TYPE: ${{ inputs.event-type }}
        ADDITIONAL_CLIENT_PAYLOAD: ${{ inputs.additional-client-payload }}
      run: |
          payload=$(jq -n \
            --arg event_type "$EVENT_TYPE" \
            --arg runner "$RUNNER" \
            '{event_type: $event_type, client_payload: {runner: $runner}}')
          
          echo "Payload: \n $payload"

          response=$( curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${ORG}/${REPO}/dispatches \
            -d "$payload" )
          
          echo $response
